name: Deploy EC2
  
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy_aws
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Deploy no EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_SSH_KEY}}
          port: 22
          script: |
            cd /home/ec2-user/portifolio

            git pull
            docker-compose up --build -d
            docker image prune -af
